= Gradle Build Cache plugin
:uri-teamcity: https://www.jetbrains.com/teamcity/[TeamCity]
:uri-gradle-docs: https://docs.gradle.org/current/userguide
:uri-gradle-build-cache: {uri-gradle-docs}/build_cache.html[Gradle Build Cache]
:uri-gradle-hazelcast-plugin: https://github.com/gradle/gradle-hazelcast-plugin
:uri-download: https://bintray.com/rodm/teamcity-plugins-generic/gradle-build-cache
:uri-apache-license: https://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0]

Gradle Build Cache is a {uri-teamcity} plugin that provides a build feature to enable the {uri-gradle-build-cache}.
The plugin applies the {uri-gradle-hazelcast-plugin}[Gradle Hazelcast] settings plugin to enable build caching
and starts a Hazelcast node on the TeamCity Server.

image:https://travis-ci.org/rodm/teamcity-gradle-build-cache-plugin.svg?branch=master["Build Status", link="https://travis-ci.org/rodm/teamcity-gradle-build-cache-plugin"]
image:https://api.bintray.com/packages/rodm/teamcity-plugins-generic/gradle-build-cache/images/download.svg[link="https://bintray.com/rodm/teamcity-plugins-generic/gradle-build-cache/_latestVersion"]

== Features

* Configures the TeamCity Server to run as a Build Cache host using Hazelcast

* Enables the Gradle Build Cache on a build configuration by adding a Build Feature

* Collects Gradle task outcomes and provides a graph on the statistics page

== Installation

* Download the plugin file from {uri-download} (see _Downloads_ section at the bottom of the page).

* Go to the plugin list of your TeamCity installation at `&lt;TeamCity URL&gt;/admin/admin.html?item=plugins` and
click on the link _Upload plugin zip_ to install the downloaded plugin file.

* Restart TeamCity.

== Using the plugin

* Edit a build configuration and add the Build Feature, Gradle Build Cache.

* Run a build that uses Gradle 3.5 or later.

The plugin applies version 0.9 of the {uri-gradle-hazelcast-plugin}[Gradle Hazelcast] plugin when Gradle 3.5 is used
and applies version 0.11 when Gradle 4.0 milestone 2 and later are used.
The version of the plugin can be overridden by setting the Java system property `teamcity.build.cache.plugin.version`
with the version to use.

If successful the build log should contain lines similar to the following:

----
[12:51:42][Step 1/1] Starting Gradle in TeamCity build 6
[12:51:43][Step 1/1] Build cache is an incubating feature.
[12:51:44][Step 1/1] Using Hazelcast node 'gradle-task-cache' at teamcity.local:5701 as local build cache, push is enabled.

... task output not shown

[12:51:46][Step 1/1] BUILD SUCCESSFUL
[12:51:46][Step 1/1]
[12:51:46][Step 1/1] Total time: 6.012 secs
[12:51:46][Step 1/1]
[12:51:46][Step 1/1] 53 tasks in build, out of which 20 (38%) were executed
[12:51:46][Step 1/1]  5   (9%) skipped
[12:51:46][Step 1/1] 11  (21%) up-to-date
[12:51:46][Step 1/1] 10  (19%) no-source
[12:51:46][Step 1/1]  7  (13%) loaded from cache
[12:51:46][Step 1/1] 20  (38%) not cacheable
[12:51:46][Step 1/1] Process exited with code 0
----

== Compatibility

The plugin is compatible with TeamCity 2018.1 and later.

== License

This plugin is available under the {uri-apache-license}.
